### ISSUE TITLE
--whitelist-file option

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/glyphhanger#15]
Similar to `glyphhanger localfile.txt` but doesn’t use phantomjs and would be faster.

**Comment by patrickkettner** [comment]
@zachleat does this mean a flag that would skip phantom loading? So `glyphhanger foo.html --whitelist-file` would treat the file as txt?

**Comment by zachleat** [comment]
@patrickkettner Yep! (now Puppeteer)

**Comment by zachleat** [comment]
@patrickkettner hmm, on re-reading this I don’t think this is accurate (based on my current understanding). I think this changed with the Puppeteer version but for any target that isn’t a valid URL, we’ll spin up a static web server and attempt to run glyphhanger against that.

That said, I filed #60 to accommodate that request.

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

The enhancement backlog can be found here: https://github.com/filamentgroup/glyphhanger/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+

Don’t forget to upvote the top comment with 👍!
