### ISSUE TITLE
private unicode ranges not subset

### ISSUE THREAD

**Issue by therealpecus** [filamentgroup/glyphhanger#18]
Hi Zach,

I am having difficulties in subsetting a font based on unicode identifiers. The font is a icon font (I know, we should be using SVGs, but this is further down the list of improvements for the website). 
The characters are unicode `E003, E008, E257, E258, E259`.
I tried with:

```
glyphhanger --subset=font.ttf --whitelist='U+E003, U+E008, U+E257-E259' --unicodes --formats=woff
```

and variants of the `--whitelist` parameter, but the font never includes the specific characters.
Could you check whether there are issues with extended range and private range unicode chars?

TIA,
Matteo

**Comment by zachleat** [comment]
The `--whitelist` param doesn’t actually support Unicode code input ranges right now. I’m going to consider this a bug—it _should_ and won’t be hard to do so.

**Comment by zachleat** [comment]
2.0 is out.
