### ISSUE TITLE
Error: Failed to launch chrome

### ISSUE THREAD

**Issue by kaushalmodi** [filamentgroup/glyphhanger#45]
Hello,

I was trying to use glyphhanger today. I am just updated to node 8.11.1 and the installation of glyphhanger finished fine. But then when I tried to do `glyphhanger https://scripter.co`, I got this error:

```
(node:24402) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/kmodi/stow/pkgs/node/8.11.1/lib/node_modules/glyphhanger/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/kmodi/stow/pkgs/node/8.11.1/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/home/kmodi/stow/pkgs/node/8.11.1/lib/node_modules/glyphhanger/node_modules/puppeteer/lib/Launcher.js:244:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
(node:24402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am on RHEL 6.6 with does very conservative updates to various libraries. I am not a web dev, but I can guess that my system lacks some libatk-bridge library?

Can you guide me better based on the above backtrace?

Thanks.

**Comment by kaushalmodi** [comment]
Oh well, looks like it's this: https://github.com/GoogleChrome/puppeteer/issues/1598

**Comment by kaushalmodi** [comment]
Oh! I need gtk3 for this to work.. can you please add that to `glyphhanger` dependency.. I will have to pass on this awesome utility till the sysadmin gods decide to update our systems to RHEL/CentOS 7+ 😞 

Ref: https://github.com/GoogleChrome/puppeteer/issues/391#issuecomment-362194153

**Comment by zachleat** [comment]
Hmm, @kaushalmodi—shouldn’t that be listed as a dependency of Chromium?

I added a section to the README pointing to the Puppeteer troubleshooting docs. https://github.com/filamentgroup/glyphhanger#troubleshooting

Do you think we need some additional notes here?
