### ISSUE TITLE
How are .ttf files reduced in size

### ISSUE THREAD

**Issue by bardware** [filamentgroup/glyphhanger#49]
Hi,

I read the documentation and it says
```
> glyphhanger --subset=*.ttf

Subsetting LatoLatin-Regular.ttf to LatoLatin-Regular-subset.ttf (was 145.06 KB, now 70.25 KB)
```
How is the reduction of the filesize achieved when no glyphs are removed (as I understand the command)?

**Comment by zachleat** [comment]
To answer this question we have to look at the DEBUG output:

> glyphhanger:subset command: 'pyftsubset test/fonts/LatoLatin-Regular.ttf --output-file=test/fonts/LatoLatin-Regular-subset.woff2 --unicodes=U+0-10FFFF --layout-features=\'*\' --flavor=woff2' +4s
> Subsetting test/fonts/LatoLatin-Regular.ttf to LatoLatin-Regular-subset.woff2 (was 145.06 KB, now 28.73 KB)

which has the `pyftsubset` command that runs:
`pyftsubset test/fonts/LatoLatin-Regular.ttf --output-file=test/fonts/LatoLatin-Regular-subset.woff2 --unicodes=U+0-10FFFF --layout-features='*' --flavor=woff2`

Not much there. So then we have to look at the `pyftsubset` manual to find the defaults that are enabled without a flag. Here’s what I found:

* `--no-desubroutinize` removes unused subroutines.
* `--drop-tables` by default is configured to drop:

```
      'BASE', 'JSTF', 'DSIG', 'EBDT', 'EBLC', 'EBSC', 'SVG ', 'PCLT', 'LTSH'
      and Graphite tables: 'Feat', 'Glat', 'Gloc', 'Silf', 'Sill'
      and color tables: 'CBLC', 'CBDT', 'sbix'
```

* `--no-subset-tables` that pyftsubset does not know about: (NOT in this list: 'gasp', 'head', 'hhea', 'maxp', 'vhea', 'OS/2', 'loca', 'name', 'cvt ', 'fpgm', 'prep', 'VMDX', 'DSIG' and 'CPAL')
* `--no-legacy-kern`: Drop TrueType 'kern' table if OpenType 'GPOS' is available
* `--name-IDs` that are not 1 or 2
* `--no-name-legacy` Drop legacy (non-Unicode) 'name' table entries
* `--name-languages` By default only records with langID 0x0409 (English) are preserved.
* `--no-glyph-names` Drop PS glyph names in TT-flavored fonts, by using 'post' table version 3.0.
* `--no-legacy-cmap` Drop the legacy 'cmap' subtables.
* `--no-symbol-cmap` Drop the 3.0 symbol 'cmap'.

For reference, here’s the output of `pyftsubset --help`: [pyftsubsethelp.txt](https://github.com/filamentgroup/glyphhanger/files/2641241/pyftsubsethelp.txt)

Please chime in if you have additional questions/comments!
