### ISSUE TITLE
Wait for document to load

### ISSUE THREAD

**Issue by bramstein** [filamentgroup/glyphhanger#5]
I may have missed this, but it doesn't appear to wait until the document has fully loaded. This means it might not grab all content.

**Comment by RoelN** [comment]
This is probably causing the difference in results here:

```
~/code 09:19:30
➤ glyphhanger https://pixelambacht.nl --spider --spider-limit=10

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_abcdefghijklmnopqrstuvwxyz{|}×–—‘’“”…™↩✓

~/code 10:05:09
➤ glyphhanger https://pixelambacht.nl --spider --spider-limit=10

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_abcdefghijklmnopqrstuvwxyz{|}×ü‑–—‘’“”…™↩◻✓
```

Both missing characters (ü and ◻) appear on the homepage from which spidering starts.

**Comment by zachleat** [comment]
Thanks!

**Comment by zachleat** [comment]
Please retest with v1.0.2, if you could!

**Comment by RoelN** [comment]
It still seems to happen with 1.0.2. It's always with the same two characters in my case, both on the homepage (the URL I feed glyphhanger).

You can test for yourself: `glyphhanger https://pixelambacht.nl --spider --spider-limit=10`

It sometimes misses the `ü` (in "...#Dynfntday 2016 in München") and the box character (in "I ◻ webfonts – Introduction to fonts...")
