### ISSUE TITLE
Add flag for disabling css output

### ISSUE THREAD

**Issue by jeremyfrank** [filamentgroup/glyphhanger#53]
It would be nice to have a flag that disables css output, something like `--no-css` or `--disable-css`. This would be helpful in cases where you have to re-subset font files and your `@font-face` rules are already defined elsewhere.

**Comment by zachleat** [comment]
I’m a little confused by this. `--css` is opt-in (not enabled by default)? So if you don’t include it with your command, it shouldn’t output the css blocks?

**Comment by jeremyfrank** [comment]
When I run glyphanger in a local directory containing fonts (`glyphhanger --subset=*.woff2`), a css file gets generated. I wasn't aware of the `--css` option, but seems like it should only be created if the option is included in the command.

_Really happy with glyphanger btw; thanks for your work on this!_

**Comment by zachleat** [comment]
Oh, yes I agree and can confirm this is happening. I think it’s a bug.

**Comment by zachleat** [comment]
Will be included with the 3.1.0 release.
