### ISSUE TITLE
how'd you come to the "Latin" subset?

### ISSUE THREAD

**Issue by olets** [filamentgroup/glyphhanger#57]
The `--LATIN` whitelist preset is the subset

```
U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD
```

That's

- Basic Latin + Latin-1 Supplement
- ı
- some of Latin Extended B
- some of Spacing Modifier Letters
- ˆ
- ˚
- ˜
- General Punctuation
- ⁴
- €
- ™
- ↑
- ↓
- −
-  ∕
- the zero width no-break space
- �

I would have expected "Latin" to mean Basic Latin and I suppose General Punctuation. This is something between what I would expect "Latin" and "Latin Extended" to mean. But maybe that's what "Latin" means in fontland? If not, wondering how you settled on that subset.

Thanks for a great tool!

**Comment by zachleat** [comment]
Good question!

It was pilfered directly from Google Fonts, seems to be somewhat standard across a few fonts:

https://fonts.googleapis.com/css?family=Open+Sans
https://fonts.googleapis.com/css?family=Roboto
https://fonts.googleapis.com/css?family=Noto+Sans

**Comment by olets** [comment]
This was buried deep in my inbox. Just coming back to say thank!
